#!/run/current-system/sw/bin/sh
A=$(lsblk | grep "sdb")
IFS=', ' read -r -a array <<< "$A"
if [ ${#array[@]} -lt 6 ]; then
  echo "-"
else
  if [ ${#array[@]} == 6 ]; then
    echo "Unmounted"
  else
    echo "${array[6]}"
  fi
fi
